//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 委托
{
    using System;
    using System.Collections.Generic;
    
    public partial class Answer
    {
        public int AID { get; set; }
        public string Title { get; set; }
        public string Text { get; set; }
        public Nullable<int> Count { get; set; }
        public Nullable<bool> BestAnswer { get; set; }
        public Nullable<System.DateTime> PostDatetime { get; set; }
        public Nullable<int> VoteNice { get; set; }
        public Nullable<int> VoteBad { get; set; }
        public Nullable<int> UID { get; set; }
        public Nullable<int> QID { get; set; }
    
        public virtual Question Question { get; set; }
        public virtual QAuser QAuser { get; set; }
    }
}
