//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 委托
{
    using System;
    using System.Collections.Generic;
    
    public partial class QAuser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public QAuser()
        {
            this.Answers = new HashSet<Answer>();
            this.Questions = new HashSet<Question>();
        }
    
        public int UID { get; set; }
        public string headimg { get; set; }
        public string UserName { get; set; }
        public string Passwd { get; set; }
        public string Sex { get; set; }
        public string Email { get; set; }
        public Nullable<int> Score { get; set; }
        public Nullable<int> RewardScore { get; set; }
        public Nullable<int> PaidScore { get; set; }
        public Nullable<int> AReCount { get; set; }
        public Nullable<int> AAcceptCount { get; set; }
        public Nullable<int> QSolvedCount { get; set; }
        public Nullable<int> QUnsolveCount { get; set; }
        public Nullable<int> QCancelledCount { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Answer> Answers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Question> Questions { get; set; }
    }
}
