//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 委托
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Question()
        {
            this.Answers = new HashSet<Answer>();
        }
    
        public int QID { get; set; }
        public string Catalog { get; set; }
        public string Tag { get; set; }
        public string Title { get; set; }
        public string Text { get; set; }
        public Nullable<int> Score { get; set; }
        public Nullable<System.DateTime> PostDatetime { get; set; }
        public Nullable<int> State { get; set; }
        public Nullable<int> Mark { get; set; }
        public Nullable<int> ViewCount { get; set; }
        public Nullable<int> UID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Answer> Answers { get; set; }
        public virtual QAuser QAuser { get; set; }
    }
}
