//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Manager.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Project_MgrEntities : DbContext
    {
        public Project_MgrEntities()
            : base("name=Project_MgrEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Message> Messages { get; set; }
        public virtual DbSet<Message_Comment> Message_Comment { get; set; }
        public virtual DbSet<Message_Type> Message_Type { get; set; }
        public virtual DbSet<Project> Projects { get; set; }
        public virtual DbSet<Task> Tasks { get; set; }
        public virtual DbSet<Task_Comment> Task_Comment { get; set; }
        public virtual DbSet<Task_List> Task_List { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<User_Project> User_Project { get; set; }
    }
}
