//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Manager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Project()
        {
            this.Task_List = new HashSet<Task_List>();
            this.User_Project = new HashSet<User_Project>();
        }
    
        public int Project_Id { get; set; }
        public string Project_Name { get; set; }
        public string Project_Customer { get; set; }
        public string Project_Detail { get; set; }
        public Nullable<System.DateTime> Project_Start_Time { get; set; }
        public Nullable<System.DateTime> Project_End_Time { get; set; }
        public Nullable<bool> Project_Is_Finished { get; set; }
        public Nullable<int> User_Id { get; set; }
    
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_List> Task_List { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User_Project> User_Project { get; set; }
    }
}
