//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Manager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task_List
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Task_List()
        {
            this.Tasks = new HashSet<Task>();
        }
    
        public int Task_List_Id { get; set; }
        public string Task_List_Name { get; set; }
        public string Task_List_Detail { get; set; }
        public Nullable<int> User_Id { get; set; }
        public Nullable<int> Project_Id { get; set; }
    
        public virtual Project Project { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task> Tasks { get; set; }
        public virtual User User { get; set; }
    }
}
